### PR TITLE
feat: add onStatus callback for iOS

### PR DESCRIPTION
**Pull request by michelalbers**
**What does it do?**

Implements the "onStatus" prop for iOS. 

**Usage** 

```JavaScript
      <NodeCameraView
        onStatus={(e) => { /*  e.nativeEvent.msg (string) & e.nativeEvent.event (int) available here */ } }
        /* ... other props here ... */
    />
```

**TODO**

* [ ] implement for android as well

### CODE REVIEW

**Comment by daxaxelrod** [comment]
Just read through the PR and it looks good to me. RN was warning about directly accessing off of UImanager and its great to see Michel refactor this. The current lib breaks in RN .60+ so this should really be looked at soon.

**Comment by daxaxelrod** [comment]
Woohoo! Thanks @illuspas

**Comment by wuxiii** [comment]
"onStatus" prop does not work for me

**Comment by michelalbers** [comment]
@wuxiii do you not receive any callbacks at all? Did you try onStatus={(e) => console.log(e)} ?

**Comment by wuxiii** [comment]
image
@michelalbers yeah, it is my usage above

**Comment by wuxiii** [comment]
sorry for my careless, NodePlayView has not to implement "onStatus" function

**Comment by michelalbers** [comment]
@wuxiii exactly :) Its only for the CameraView.

**Comment by ManigandanRaamanathan** [comment]
@michelalbers @daxaxelrod @illuspas the onState not returning any nativeEvents. The data is always null on iOS

**Comment by ManigandanRaamanathan** [comment]
@michelalbers its working fine for android. But its missing in iOS. @wuxiii any update?

**Pull request merged**
