### PR TITLE
Added audioEnable props to NodePlayerView

### PR DESCRIPTION
**Pull request by lethienhung**

### CODE REVIEW

**Comment by rehamkhawajahere** [comment]
Switching this property using state not helping in IOS.

**Comment by frank505** [comment]
@rehamkhawajahere  does Nodeplayerview audio work on ios for you? if it does please what version are you using i am stuck right now :(

**Comment by lethienhung** [comment]
I'm using v0.2.13 and works on iOS properly

**Comment by frank505** [comment]
@lethienhung what version of react-native are you using also :) ?

**Comment by lethienhung** [comment]
@frank505 I'm using react-native 0.63.2

**Comment by rehamkhawajahere** [comment]
@lethienhung Did you tried toggling the audio on IOS using state?

**Pull request merged**
